### PR TITLE
19 - Underlined heading 

### LINKED ISSUE #19: Headings with Horizontal Rule
Screenshot 2023-09-11 at 5 53 34 PM

Screenshot 2023-09-11 at 5 48 13 PM

Screenshot 2023-09-11 at 5 47 37 PM

### PR DESCRIPTION
**Pull request by laith-adobe**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #19

Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.page/health-wellness-deals
- After: https://underlined-heading--walgreens--hlxsites.hlx.page/health-wellness-deals

### CODE REVIEW

**Review by mtemk — APPROVED** [review]
Changes tested and working properly based on the fix. Good job. 

Just a heads up to update the "after" test url link to: https://underlined-heading--walgreens--hlxsites.hlx.page/health-wellness-deals (currently it's: https://undelined-heading--walgreens--hlxsites.hlx.page/health-wellness-deals).

**Review by mtemk — CHANGES_REQUESTED** [review]
The changes look good but I think we need to check the lighthouse score before merging (not at 100 currently after additional changes).

**Comment by laith-adobe** [comment]
Screenshot 2023-09-14 101331
@mtemk manual testing show light house score at 100

**Review by mtemk — APPROVED** [review]
Reaches 100 lighthouse score manually but good to double-check why Helix Bot is showing 98 for one of the pages.

**Pull request merged**
